version: '3'
services:

  backend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"

  db:
    image: postgres
    restart: always
    shm_size: 128mb
    environment:
      POSTGRES_HOST: dpg-cpl72h7109ks73dn8ge0-a
      POSTGRES_USER: root
      POSTGRES_PASSWORD: njKPyUTwLl6adBIT38aCAlpG8M695Hnq
      POSTGRES_DB: dbname_jnpp
    ports:
      - 5432:5432

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080